### ISSUE TITLE
生成图像颜色问题

### ISSUE THREAD

**Issue by ghost** [294coder/Dif-PAN#4]
曹博士您好，您的工作非常出色，您的代码也非常清晰和完整。想请教如何能生成和您文中相同的图像颜色，目前能够做到和您arXiv上初稿DDRF的图像结果相同，但是和您发表的结果颜色不同，想请教您应该如何去做。gf2的图像颜色发黄，wv3结果和pancollection数据集的demo图像颜色一样，但是想做到您文中的图片效果需要怎么做，希望您闲暇时能帮我解惑。
感谢！
祝好！

**Comment by Py-JLc** [comment]
目前能够做到和您arxiv上初稿ddrf的结果都相同，但是和您发表的ddif的结果颜色不同，想请教您应该如何去做。

**Comment by 294coder** [comment]
I‘ve reply to your email. Please check it.
